// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHseMRCuoR4vYMO6Ux4AjWh_xU26eJGPI',
    appId: '1:533939673134:web:9e4ca32b48b63b5ae027bf',
    messagingSenderId: '533939673134',
    projectId: 'musicapp-3a633',
    authDomain: 'musicapp-3a633.firebaseapp.com',
    storageBucket: 'musicapp-3a633.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5s6rr6BU1B72Njp5OrqdWUqQN5dxsi-s',
    appId: '1:533939673134:android:3f72a216e2ea9e97e027bf',
    messagingSenderId: '533939673134',
    projectId: 'musicapp-3a633',
    storageBucket: 'musicapp-3a633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopzMkLaKfxWlIOVsR9adGFtXYw7I4__A',
    appId: '1:533939673134:ios:fa5f9cb358ab7b28e027bf',
    messagingSenderId: '533939673134',
    projectId: 'musicapp-3a633',
    storageBucket: 'musicapp-3a633.appspot.com',
    iosClientId: '533939673134-f1padkdp7dd0ovfbmnknqrm13qu8pohm.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopzMkLaKfxWlIOVsR9adGFtXYw7I4__A',
    appId: '1:533939673134:ios:0e2b0dd57052e603e027bf',
    messagingSenderId: '533939673134',
    projectId: 'musicapp-3a633',
    storageBucket: 'musicapp-3a633.appspot.com',
    iosClientId: '533939673134-1jq4f3a958u73pkcs2pqf9pio7v6h4bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp.RunnerTests',
  );
}
